spring.application.name=Reportes-de-danos-urbanos
spring.datasource.url=jdbc:postgresql://ep-muddy-cherry-add69683-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vf2FMunSGib7
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# ==========================
#  Auth0 (JWT Resource Server)
# ==========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-fok5n051icyr2hf1.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://api.mapa-riesgos


# ==========================
#  CORS (Angular local)
# ==========================
# Nota: el origen también lo habilitaremos en SecurityConfig.java
app.cors.allowed-origin=http://localhost:4200,https://mapa-riesgo-code-1.onrender.com
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=ALWAYS

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
